Add `Android` support
holepunchto/liblog pull request #1
Opened 2024-08-08 14:52 UTC by yassernasc

2024-08-08 14:56 UTC, yassernasc commented on CMakeLists.txt
> +  target_link_libraries(
It was a solution for: https://stackoverflow.com/questions/4455941/undefined-reference-to-android-log-print
probably not the best approach

2024-08-08 15:34 UTC, kasperisager requested changes

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  int flags;
```suggestion
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  log_->flags = flags;
```suggestion
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  if (log_ == NULL) goto done;
```suggestion
  if (log_ == NULL) return -1;
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +}
```suggestion
```

Android already support formatted printing so this function isn't required.

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  err = __android_log_vprint(ANDROID_LOG_DEBUG, log_->name, "%s", args);
```suggestion
  int err = __android_log_vprint(ANDROID_LOG_DEBUG, log_->name, message, args);
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  err = __android_log_vprint(ANDROID_LOG_INFO, log_->name, "%s", args);
```suggestion
  int err = __android_log_vprint(ANDROID_LOG_INFO, log_->name, message, args);
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  err = __android_log_vprint(ANDROID_LOG_WARN, log_->name, "%s", args);
```suggestion
  int err = __android_log_vprint(ANDROID_LOG_WARN, log_->name, message, args);
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  err = __android_log_vprint(ANDROID_LOG_ERROR, log_->name, "%s", args);
```suggestion
  int err = __android_log_vprint(ANDROID_LOG_ERROR, log_->name, message, args);
```

2024-08-08 15:34 UTC, kasperisager commented on src/android.c
> +  exit(1);
```suggestion
  __android_log_vprint(ANDROID_LOG_FATAL, log_->name, message, args);

  exit(1);
```

2024-08-08 15:34 UTC, kasperisager commented on CMakeLists.txt
> +  )
```suggestion
  find_library(log log)

  target_link_libraries(
    log
    PUBLIC
      ${log}
  )
```

2024-08-12 20:37 UTC, yassernasc commented
All comments are fixed, I think the only thing missing is to add Android support at `.github/workflows/test.yml`

2024-08-13 09:06 UTC, kasperisager approved these changes

2024-08-13 09:07 UTC, kasperisager commented
Woop! 🥳

2024-08-13 09:08 UTC, merged